// Auto-generated by scripts/generate-project.ts for network: megaeth-mainnet
// Do not edit manually. Run: npm run generate-project megaeth-mainnet

import {
  EthereumProject,
  EthereumDatasourceKind,
  EthereumHandlerKind,
} from "@subql/types-ethereum";

const project: EthereumProject = {
  specVersion: "1.0.0",
  version: "0.0.4",
  name: "uniswap-v4-subquery-megaeth-mainnet",
  description:
    "Uniswap V4 SubQuery indexer for megaeth-mainnet",
  runner: {
    node: {
      name: "@subql/node-ethereum",
      version: ">=6.0.0",
    },
    query: {
      name: "@subql/query",
      version: "*",
    },
  },
  schema: {
    file: "./schema.graphql",
  },
  network: {
    chainId: "648",
    endpoint: ["https://rpc.megaeth.com"],
  },
  dataSources: [
    {
      kind: EthereumDatasourceKind.Runtime,
      startBlock: 3637446,
      options: {
        abi: "PoolManager",
        address: "0x58dd83c317b03e6ebd72c3e912adf60a8e97aa95",
      },
      assets: new Map([
        ["ERC20", { file: "./abis/ERC20.json" }],
        ["ERC20SymbolBytes", { file: "./abis/ERC20SymbolBytes.json" }],
        ["ERC20NameBytes", { file: "./abis/ERC20NameBytes.json" }],
        ["PoolManager", { file: "./abis/PoolManager.json" }],
        // Include all Hook ABIs for type generation
        ["EulerSwapFactory", { file: "./abis/EulerSwapFactory.json" }],
        ["ArrakisHookFactory", { file: "./abis/ArrakisHookFactory.json" }],
      ]),
      mapping: {
        file: "./dist/index.js",
        handlers: [
          {
            kind: EthereumHandlerKind.Event,
            handler: "handleInitialize",
            filter: {
              topics: [
                "Initialize(bytes32,address,address,uint24,int24,address,uint160,int24)",
              ],
            },
          },
          {
            kind: EthereumHandlerKind.Event,
            handler: "handleModifyLiquidity",
            filter: {
              topics: [
                "ModifyLiquidity(bytes32,address,int24,int24,int256,bytes32)",
              ],
            },
          },
          {
            kind: EthereumHandlerKind.Event,
            handler: "handleSwap",
            filter: {
              topics: [
                "Swap(bytes32,address,int128,int128,uint160,uint128,int24,uint24)",
              ],
            },
          },
        ],
      },
    },
    {
      kind: EthereumDatasourceKind.Runtime,
      startBlock: 3637446,
      options: {
        abi: "PositionManager",
        address: "0xcae584c1f193cb3c090324ca8a1af4ce378e37e1",
      },
      assets: new Map([
        ["PositionManager", { file: "./abis/PositionManager.json" }],
      ]),
      mapping: {
        file: "./dist/index.js",
        handlers: [
          {
            kind: EthereumHandlerKind.Event,
            handler: "handleSubscription",
            filter: { topics: ["Subscription(uint256,address)"] },
          },
          {
            kind: EthereumHandlerKind.Event,
            handler: "handleUnsubscription",
            filter: { topics: ["Unsubscription(uint256,address)"] },
          },
          {
            kind: EthereumHandlerKind.Event,
            handler: "handleTransfer",
            filter: { topics: ["Transfer(address,address,uint256)"] },
          },
        ],
      },
    }
  ],
  repository: "https://github.com/Uniswap/v4-subgraph",
};

export default project;
