// Auto-generated by scripts/generate-project.ts for network: mainnet
// Do not edit manually. Run: npm run generate-project mainnet

import { NetworkName } from './network-types'

/**
 * The network name for this deployment.
 * This is set at build time based on the network specified during project generation.
 */
export const RUNTIME_NETWORK: NetworkName = NetworkName.MAINNET

/**
 * The chain ID for this deployment.
 * This is set at build time based on the network specified during project generation.
 */
export const RUNTIME_CHAIN_ID = '1'
